### ISSUE TITLE
mpd

### ISSUE THREAD

**Issue by s03i0path** [yurihikari/garuda-sway-config#3]
ncmpcpp doesn't play any song ...
after clicking on song, it stop right away

**Comment by yurihikari** [comment]
Hi,
Are you using sway or hyprland?
If you are using sway, I just pushed a fix for the missing line to launch mpd at startup : [This commit](https://github.com/yurihikari/garuda-sway-config/commit/868cb1310971a720e39bf06999a345a54da69b0d), tell me if this fixed your issue.

If you are using hyprland, did you check if your mpd was running correctly? ( do the command mpd to check if it's already running, it should say **"Failed to bind to '[::]:6600'; Failed to bind socket: Address already in use"** if it was already running ) . If there is any error or mpd not launching properly, there should be logs inside the log file in **~/.config/mpd/log**

I am personally not using ncmpcpp, so if the problem ends up being this, I may have trouble trying to help you to fix that issue if the previous steps didn't help.

**Comment by yurihikari** [comment]
Since you are not replying after a while, I'm considering this issue fixed. If you still need help, I'll reopen it.
