### ISSUE TITLE
How to set wallpaper?

### ISSUE THREAD

**Issue by purplekairi1312** [yurihikari/garuda-sway-config#4]
Hi sorry if its a dumb question but I have no wallpaper and I dont get how to set up properly the wallpaper

**Comment by yurihikari** [comment]
Both sway and hyprland uses swaybg as wallpaper handler in my config.

You can manually set a wallpaper with 
```bash
swaybg --output '*' --mode fill --image /path/to/your/wallpaper &
```

In the **~/.config/hypr/scripts/startup** script and in the **~/.config/sway/config** file.

If you use my config, there should be a script to switch between wallpapers you want without editing yourself the configs by using **Meta+LeftShift+B**. You just need to put the wallpapers you want inside the **~/.config/sway/backgrounds** directory. 
If you want to change the wallpapers directory, go inside **~/.config/hypr/scripts/background** and **~/.config/sway/scripts/background-swap.sh** and replace the 
```bash
BACKGROUND_DIR="$HOME/.config/sway/backgrounds"
```
line with 
```bash
BACKGROUND_DIR="path/to/your/wallpapers/directory"
```

**Comment by yurihikari** [comment]
I'm closing that issue. If you still need help, I'll reopen it.
