### ISSUE TITLE
What is the neofetch theme in the preview pics?

### ISSUE THREAD

**Issue by Momen-MKadry** [yurihikari/garuda-sway-config#8]
This one, couldn't find it in the neofetch config files in the repo

![image](https://github.com/user-attachments/assets/79325911-1ac7-46ba-9b0d-ff442e0715c4)

**Comment by yurihikari** [comment]
This is fastfetch, I stopped using neofetch since it's not maintained anymore.

**Comment by Momen-MKadry** [comment]
Ok thanks
